{
 "title": "Speedtest",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Last Download Speed",
   "type": "stat",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Upload Speed",
   "type": "stat",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upload_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Ping",
   "type": "stat",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download Speed History",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expr": "download_speed", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Upload Speed History",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expr": "upload_speed", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "Ping History",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ping", "legendFormat": "Ping" }
   ]
  }
 ]
}